using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using DHondtSymTest2.Geography;

namespace DHondtSymTest2.Politics
{
	public enum OkregOszacowaniaEnum
	{
		Legnica = 1,
		Walbrzych,
		Wroclaw,
		Bydgoszcz,
		Torun,
		Lublin,
		Chelm,
		ZielonaGora,
		Lodz,
		PiotrkowTrybunalski,
		Sieradz,
		Krakow12,
		Krakow13,
		NowySacz,
		Tarnow,
		Plock,
		Radom,
		Siedlce,
		Warszawa19,
		Warszawa20,
		Opole,
		Krosno,
		Rzeszow,
		Bialystok,
		Gdansk,
		Gdynia,
		BielskoBiala,
		Czestochowa,
		Gliwice,
		Rybnik,
		Katowice,
		Sosnowiec,
		Kielce,
		Elblag,
		Olsztyn,
		Kalisz,
		Konin,
		Pila,
		Poznan,
		Koszalin,
		Szczecin,
	}

	[DebuggerDisplay("{Numer}: {Nazwa}")]
	public class OkregOszacowania
	{
		public OkregOszacowaniaEnum Enum;
		public int Numer;
		public string Nazwa;
		public int OgolnieMandaty;
		public OszacowaniePartie<int> Glosy = new OszacowaniePartie<int>();
		public OszacowaniePartie<int> ObliczoneMandaty = new OszacowaniePartie<int>();
		public List<JednostkaTerytorialna> JednostkiTerytorialne = new List<JednostkaTerytorialna>();
	}

	public static class Oszacowanie
	{
		public static readonly Dictionary<OkregOszacowaniaEnum, OkregOszacowania> Okregi;

		static Oszacowanie()
		{
			Okregi = new List<OkregOszacowania>
			{
				#region Okregi = new OkregOszacowania[]
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Legnica, Numer = 1, Nazwa = "Legnica", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Walbrzych, Numer = 2, Nazwa = "Wałbrzych", OgolnieMandaty = 8, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Wroclaw, Numer = 3, Nazwa = "Wrocław", OgolnieMandaty = 14, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Bydgoszcz, Numer = 4, Nazwa = "Bydgoszcz", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Torun, Numer = 5, Nazwa = "Toruń", OgolnieMandaty = 13, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Lublin, Numer = 6, Nazwa = "Lublin", OgolnieMandaty = 15, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Chelm, Numer = 7, Nazwa = "Chełm", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.ZielonaGora, Numer = 8, Nazwa = "Zielona Góra", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Lodz, Numer = 9, Nazwa = "Łódź", OgolnieMandaty = 10, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.PiotrkowTrybunalski, Numer = 10, Nazwa = "Piotrków Trybunalski", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Sieradz, Numer = 11, Nazwa = "Sieradz", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Krakow12, Numer = 12, Nazwa = "Kraków", OgolnieMandaty = 8, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Krakow13, Numer = 13, Nazwa = "Kraków", OgolnieMandaty = 14, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.NowySacz, Numer = 14, Nazwa = "Nowy Sącz", OgolnieMandaty = 10, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Tarnow, Numer = 15, Nazwa = "Tarnów", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Plock, Numer = 16, Nazwa = "Płock", OgolnieMandaty = 10, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Radom, Numer = 17, Nazwa = "Radom", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Siedlce, Numer = 18, Nazwa = "Siedlce", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Warszawa19, Numer = 19, Nazwa = "Warszawa", OgolnieMandaty = 20, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Warszawa20, Numer = 20, Nazwa = "Warszawa", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Opole, Numer = 21, Nazwa = "Opole", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Krosno, Numer = 22, Nazwa = "Krosno", OgolnieMandaty = 11, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Rzeszow, Numer = 23, Nazwa = "Rzeszów", OgolnieMandaty = 15, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Bialystok, Numer = 24, Nazwa = "Białystok", OgolnieMandaty = 14, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Gdansk, Numer = 25, Nazwa = "Gdańsk", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Gdynia, Numer = 26, Nazwa = "Gdynia", OgolnieMandaty = 14, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.BielskoBiala, Numer = 27, Nazwa = "Bielsko-Biała", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Czestochowa, Numer = 28, Nazwa = "Częstochowa", OgolnieMandaty = 7, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Gliwice, Numer = 29, Nazwa = "Gliwice", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Rybnik, Numer = 30, Nazwa = "Rybnik", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Katowice, Numer = 31, Nazwa = "Katowice", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Sosnowiec, Numer = 32, Nazwa = "Sosnowiec", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Kielce, Numer = 33, Nazwa = "Kielce", OgolnieMandaty = 16, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Elblag, Numer = 34, Nazwa = "Elbląg", OgolnieMandaty = 8, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Olsztyn, Numer = 35, Nazwa = "Olsztyn", OgolnieMandaty = 10, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Kalisz, Numer = 36, Nazwa = "Kalisz", OgolnieMandaty = 12, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Konin, Numer = 37, Nazwa = "Konin", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Pila, Numer = 38, Nazwa = "Piła", OgolnieMandaty = 9, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Poznan, Numer = 39, Nazwa = "Poznań", OgolnieMandaty = 10, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Koszalin, Numer = 40, Nazwa = "Koszalin", OgolnieMandaty = 8, },
				new OkregOszacowania { Enum = OkregOszacowaniaEnum.Szczecin, Numer = 41, Nazwa = "Szczecin", OgolnieMandaty = 12, },
				#endregion
			}
			.ToDictionary(o => o.Enum);

			var powiazania = new List<dynamic>
			{
				#region new { PowiatTeryt = 
				new { PowiatTeryt = new Teryt("0201"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0202"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0203"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0204"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0205"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0206"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0207"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0208"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0209"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0210"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0211"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0212"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0213"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0214"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0215"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0216"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0217"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0218"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0219"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0220"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0221"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0222"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0223"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0224"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0225"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0226"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0261"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0262"), OkregNr = 1 },
				new { PowiatTeryt = new Teryt("0264"), OkregNr = 3 },
				new { PowiatTeryt = new Teryt("0265"), OkregNr = 2 },
				new { PowiatTeryt = new Teryt("0401"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0402"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0403"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0404"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0405"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0406"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0407"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0408"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0409"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0410"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0411"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0412"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0413"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0414"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0415"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0416"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0417"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0418"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0419"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0461"), OkregNr = 4 },
				new { PowiatTeryt = new Teryt("0462"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0463"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0464"), OkregNr = 5 },
				new { PowiatTeryt = new Teryt("0601"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0602"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0603"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0604"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0605"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0606"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0607"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0608"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0609"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0610"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0611"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0612"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0613"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0614"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0615"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0616"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0617"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0618"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0619"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0620"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0661"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0662"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0663"), OkregNr = 6 },
				new { PowiatTeryt = new Teryt("0664"), OkregNr = 7 },
				new { PowiatTeryt = new Teryt("0801"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0802"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0803"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0804"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0805"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0806"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0807"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0808"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0809"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0810"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0811"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0812"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0861"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("0862"), OkregNr = 8 },
				new { PowiatTeryt = new Teryt("1001"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1002"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1003"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1004"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1005"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1006"), OkregNr = 9 },
				new { PowiatTeryt = new Teryt("1007"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1008"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1009"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1010"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1011"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1012"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1013"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1014"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1015"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1016"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1017"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1018"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1019"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1020"), OkregNr = 11 },
				new { PowiatTeryt = new Teryt("1021"), OkregNr = 9 },
				new { PowiatTeryt = new Teryt("1061"), OkregNr = 9 },
				new { PowiatTeryt = new Teryt("1062"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1063"), OkregNr = 10 },
				new { PowiatTeryt = new Teryt("1201"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1202"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1203"), OkregNr = 12 },
				new { PowiatTeryt = new Teryt("1204"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1205"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1206"), OkregNr = 13 },
				new { PowiatTeryt = new Teryt("1207"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1208"), OkregNr = 13 },
				new { PowiatTeryt = new Teryt("1209"), OkregNr = 12 },
				new { PowiatTeryt = new Teryt("1210"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1211"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1212"), OkregNr = 13 },
				new { PowiatTeryt = new Teryt("1213"), OkregNr = 12 },
				new { PowiatTeryt = new Teryt("1214"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1215"), OkregNr = 12 },
				new { PowiatTeryt = new Teryt("1216"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1217"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1218"), OkregNr = 12 },
				new { PowiatTeryt = new Teryt("1219"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1261"), OkregNr = 13 },
				new { PowiatTeryt = new Teryt("1262"), OkregNr = 14 },
				new { PowiatTeryt = new Teryt("1263"), OkregNr = 15 },
				new { PowiatTeryt = new Teryt("1401"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1402"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1403"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1404"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1405"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1406"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1407"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1408"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1409"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1410"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1411"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1412"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1413"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1414"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1415"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1416"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1417"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1418"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1419"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1420"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1421"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1422"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1423"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1424"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1425"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1426"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1427"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1428"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1429"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1430"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1432"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1433"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1434"), OkregNr = 20 },
				new { PowiatTeryt = new Teryt("1435"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1436"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1437"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1438"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1461"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1462"), OkregNr = 16 },
				new { PowiatTeryt = new Teryt("1463"), OkregNr = 17 },
				new { PowiatTeryt = new Teryt("1464"), OkregNr = 18 },
				new { PowiatTeryt = new Teryt("1465"), OkregNr = 19 },
				new { PowiatTeryt = new Teryt("1601"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1602"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1603"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1604"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1605"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1606"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1607"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1608"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1609"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1610"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1611"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1661"), OkregNr = 21 },
				new { PowiatTeryt = new Teryt("1801"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1802"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1803"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1804"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1805"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1806"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1807"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1808"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1809"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1810"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1811"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1812"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1813"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1814"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1815"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1816"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1817"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1818"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1819"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1820"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1821"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1861"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1862"), OkregNr = 22 },
				new { PowiatTeryt = new Teryt("1863"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("1864"), OkregNr = 23 },
				new { PowiatTeryt = new Teryt("2001"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2002"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2003"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2004"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2005"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2006"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2007"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2008"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2009"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2010"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2011"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2012"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2013"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2014"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2061"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2062"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2063"), OkregNr = 24 },
				new { PowiatTeryt = new Teryt("2201"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2202"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2203"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2204"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2205"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2206"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2207"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2208"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2209"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2210"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2211"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2212"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2213"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2214"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2215"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2216"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2261"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2262"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2263"), OkregNr = 26 },
				new { PowiatTeryt = new Teryt("2264"), OkregNr = 25 },
				new { PowiatTeryt = new Teryt("2401"), OkregNr = 32 },
				new { PowiatTeryt = new Teryt("2402"), OkregNr = 27 },
				new { PowiatTeryt = new Teryt("2403"), OkregNr = 27 },
				new { PowiatTeryt = new Teryt("2404"), OkregNr = 28 },
				new { PowiatTeryt = new Teryt("2405"), OkregNr = 29 },
				new { PowiatTeryt = new Teryt("2406"), OkregNr = 28 },
				new { PowiatTeryt = new Teryt("2407"), OkregNr = 28 },
				new { PowiatTeryt = new Teryt("2408"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2409"), OkregNr = 28 },
				new { PowiatTeryt = new Teryt("2410"), OkregNr = 27 },
				new { PowiatTeryt = new Teryt("2411"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2412"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2413"), OkregNr = 29 },
				new { PowiatTeryt = new Teryt("2414"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2415"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2416"), OkregNr = 32 },
				new { PowiatTeryt = new Teryt("2417"), OkregNr = 27 },
				new { PowiatTeryt = new Teryt("2461"), OkregNr = 27 },
				new { PowiatTeryt = new Teryt("2462"), OkregNr = 29 },
				new { PowiatTeryt = new Teryt("2463"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2464"), OkregNr = 28 },
				new { PowiatTeryt = new Teryt("2465"), OkregNr = 32 },
				new { PowiatTeryt = new Teryt("2466"), OkregNr = 29 },
				new { PowiatTeryt = new Teryt("2467"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2468"), OkregNr = 32 },
				new { PowiatTeryt = new Teryt("2469"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2470"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2471"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2472"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2473"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2474"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2475"), OkregNr = 32 },
				new { PowiatTeryt = new Teryt("2476"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2477"), OkregNr = 31 },
				new { PowiatTeryt = new Teryt("2478"), OkregNr = 29 },
				new { PowiatTeryt = new Teryt("2479"), OkregNr = 30 },
				new { PowiatTeryt = new Teryt("2601"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2602"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2603"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2604"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2605"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2606"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2607"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2608"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2609"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2610"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2611"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2612"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2613"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2661"), OkregNr = 33 },
				new { PowiatTeryt = new Teryt("2801"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2802"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2803"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2804"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2805"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2806"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2807"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2808"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2809"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2810"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2811"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2812"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2813"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2814"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2815"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2816"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2817"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2818"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2819"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("2861"), OkregNr = 34 },
				new { PowiatTeryt = new Teryt("2862"), OkregNr = 35 },
				new { PowiatTeryt = new Teryt("3001"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3002"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3003"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3004"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3005"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3006"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3007"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3008"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3009"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3010"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3011"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3012"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3013"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3014"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3015"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3016"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3017"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3018"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3019"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3020"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3021"), OkregNr = 39 },
				new { PowiatTeryt = new Teryt("3022"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3023"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3024"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3025"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3026"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3027"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3028"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3029"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3030"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3031"), OkregNr = 38 },
				new { PowiatTeryt = new Teryt("3061"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3062"), OkregNr = 37 },
				new { PowiatTeryt = new Teryt("3063"), OkregNr = 36 },
				new { PowiatTeryt = new Teryt("3064"), OkregNr = 39 },
				new { PowiatTeryt = new Teryt("3201"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3202"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3203"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3204"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3205"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3206"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3207"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3208"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3209"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3210"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3211"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3212"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3213"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3214"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3215"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3216"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3217"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3218"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3261"), OkregNr = 40 },
				new { PowiatTeryt = new Teryt("3262"), OkregNr = 41 },
				new { PowiatTeryt = new Teryt("3263"), OkregNr = 41 },
				#endregion
			}
			.ToDictionary(x => x.PowiatTeryt);

			//powiazania.Values.Select(x => x.);

			foreach (var p in powiazania.Values)
			{
				var okreg = Okregi[(OkregOszacowaniaEnum)p.OkregNr];
				var powiat = Polska.Powiaty[p.PowiatTeryt];
				okreg.JednostkiTerytorialne.Add(powiat);
			}

		}

	}
}
